services:
  html2b-render:
    image: html2b-render:poc
    build:
      context: .
      dockerfile: src/api/Html2b.Render/Dockerfile
    ports:
      - "127.0.0.1:8081:8080"
    stop_grace_period: 30s
