@Html2b.ApiFunctions_HostAddress = http://localhost:8080

GET {{Html2b.ApiFunctions_HostAddress}}/health/live

###

GET {{Html2b.ApiFunctions_HostAddress}}/health/ready

###

POST {{Html2b.ApiFunctions_HostAddress}}/api/renders/png

###

POST {{Html2b.ApiFunctions_HostAddress}}/api/renders/jpeg

###

POST {{Html2b.ApiFunctions_HostAddress}}/api/renders/pdf

###

POST {{Html2b.ApiFunctions_HostAddress}}/api/renders/gif

###
