using '../main.bicep'

param environmentName = 'dev'
param location = 'westus2'
param resourceGroupName = 'rg-html2b-dev'
param containerRegistryName = 'crhtml2bdev'
param imageRepositoryName = 'html2b-render'
param logWorkspaceName = 'log-html2b-dev'
param logRetentionDays = 30
param containerEnvName = 'cae-html2b-dev'
param deploymentIdentityName = 'id-html2b-infrastructure-dev'
param githubCredentialName = 'github-environment-dev'
param githubRepository = 'george-pov/html2b'
param githubEnvironmentName = 'dev'
param functionStorageName = 'sthtml2bfuncdev'
param functionPlanName = 'plan-html2b-functions-dev'
param applicationInsightsName = 'appi-html2b-dev'
param functionAppName = 'func-html2b-api-dev'
param functionReleaseContainer = 'function-releases'
param functionRuntime = 'dotnet-isolated'
param functionRuntimeVersion = '10.0'
param functionInstanceMemoryMb = 2048
param functionMaxInstances = 1
param renderApiClientId = '78ae23b3-bca7-4129-bd47-532b96429a96'
param renderIdentityName = 'id-html2b-render-dev'
param renderContainerAppName = 'ca-html2b-render-dev'
